In [1]:
import pandas as pd

In [10]:
csv_links= [
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/anscombe.csv",
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/anagrams.csv"]

In [11]:
df_dataframes = []

In [12]:
for link in csv_links:
    df = pd.read_csv(link)
    df_dataframes.append(df)

In [15]:
df_dataframes[0].head()

  dataset     x     y
0       I  10.0  8.04
1       I   8.0  6.95
2       I  13.0  7.58
3       I   9.0  8.81
4       I  11.0  8.33

In [16]:
df_dataframes[1].tail()

    subidr    attnr  num1  num2  num3
15      16  focused     6   8.0     7
16      17  focused     7   7.0     6
17      18  focused     7   8.0     6
18      19  focused     5   6.0     6
19      20  focused     6   6.0     5

In [17]:
df_dataframes[0].shape

(44, 3)